---
title: "country_collaborations"
author: "LR"
date: "2022-11-01"
output: html_document
editor_options: 
  chunk_output_type: console
---
# Circular plots country collaborations
### Load packages
```{r setup, echo = FALSE, results = 'hide'}
library(bibliometrix)
library(here)
library(circlize)
library(wesanderson)
library(tidyverse)
library(bibtex)
```
### Load files
```{r setup, echo = FALSE, results = 'hide'}
# #Bibliometric data of included papers (with references) dwonloaded from Scopus in .bib format:
# bib_sco <- convert2df(here("data","scopus.bib"),
#                       dbsource = "scopus",
#                       format = "bibtex")
# #dim(bib_sco) #8 rows 33 columns
# 
# #Extra four studies founded searching on Scopus using the DOIs:
# bib_sco2 <- convert2df(here("data","scopus2.bib"),
#                        dbsource = "scopus",
#                        format = "bibtex")
# 
# #Merging the two .bib files:
# bib <-
#   bind_rows(bib_sco, bib_sco2)
# 
# bib2 <- metaTagExtraction(bib, Field = "AU1_CO",
#                           sep = ";")
# 
# bib2 <- metaTagExtraction(bib2, Field = "AU_CO", sep = ";")

#write.csv(bib2, here("data", "biblio.csv"), row.names = FALSE)

bib2 <- read.csv(here("data", "biblio.csv"))

```
### Making the plot without getting rid of collabs with the same country
```{r, echo = FALSE, results = 'hide'}
NetMatrix2 <- biblioNetwork(bib2, 
                            analysis = "collaboration",
                            network = "countries", 
                            sep = ";")

net_matrix2 <- as.matrix(NetMatrix2)

#net_matrix2 <- net_matrix2[rownames(NetMatrix2), countries]
#diag(net_matrix2) <- 0 #get rid of collaboration with same country

#net_matrix2

# getting rid of lower triangle (as this is duplication of info)
net_matrix2[lower.tri(net_matrix2)] <- 0 
#colnames(net_matrix2) - change to title case:
colnames(net_matrix2) <- str_to_title(colnames(net_matrix2))
#rownames(net_matrix2) - change to title case:
rownames(net_matrix2) <- str_to_title(rownames(net_matrix2))
#Fix "Usa" to "USA" :
colnames(net_matrix2)[colnames(net_matrix2) == "Usa"] <- "USA"
rownames(net_matrix2)[rownames(net_matrix2) == "Usa"] <- "USA"
#change "UNITED KINGDOM" to "UK" for easier plotting:
colnames(net_matrix2)[colnames(net_matrix2) == "United Kingdom"] <- "UK"
rownames(net_matrix2)[rownames(net_matrix2) == "United Kingdom"] <- "UK"

circos.clear()

my.cols2 <- c(USA = "#00FFFF",
              China = "#89CFF0",
              Spain = "#7393B3", 
              Denmark = "#088F8F", 
              Italy = "#9FE2BF",
              France = "#EADDCA",
              Sweden = "#E1C16E",
              Canada = "#CD7F32", 
              Norway = "#A52A2A",
              UK = "#DAA06D", 
              Korea = "#800020", 
              Greece = "#E97451", 
              Germany = "#F0E68C",
              Australia = "#808000", 
              Brazil = "#FFAC1C", 
              Finland = "#E3963E",
              Austria = "#FBCEB1", 
              Belgium = "#FFC000", 
              Malaysia = "#F4BB44",
              Netherlands = "#FFE5B4", 
              Poland = "#FF4433",
              Switzerland = "#FA8072",
              Romania = "#FFF5EE",
              Slovenia = "#9F2B68",
              Uganda = "#DE3163",
              Cyprus = "#811331",
              Hong_Kong = "#DC143C",
              Japan = "#AA336A", 
              Czech_Republic = "#C9A9A6", 
              Ghana = "#FF69B4",
              Hungary = "#673147", 
              India = "#E30B5C", 
              Israel = "#D8BFD8", 
              Kenya = "#DA70D6",
              Luxembourg = "#770737",
              Mexico = "#E0B0FF",
              Monaco = "#CCCCFF", 
              Portugal = "#A95C68", 
              Saudi_Arabia = "#51414F", 
              Singapore = "#BDB5D5", 
              Slovakia = "#FAF9F6",
              South_Africa = "#EEDC82", 
              Tanzania = "#DAA520", 
              Zimbabwe = "#F0E68C")

colnames(net_matrix2)[colnames(net_matrix2) == "Hong Kong"] <- "Hong_Kong"
rownames(net_matrix2)[rownames(net_matrix2) == "Hong Kong"] <- "Hong_Kong"
colnames(net_matrix2)[colnames(net_matrix2) == "Czech Republic"] <- "Czech_Republic"
rownames(net_matrix2)[rownames(net_matrix2) == "Czech Republic"] <- "Czech_Republic"
colnames(net_matrix2)[colnames(net_matrix2) == "Saudi Arabia"] <- "Saudi_Arabia"
rownames(net_matrix2)[rownames(net_matrix2) == "Saudi Arabia"] <- "Saudi_Arabia"
colnames(net_matrix2)[colnames(net_matrix2) == "South Africa"] <- "South_Africa"
rownames(net_matrix2)[rownames(net_matrix2) == "South Africa"] <- "South_Africa"



fig1 <- chordDiagram(net_matrix2,
               annotationTrack = "grid",
               preAllocateTracks = 1, 
               grid.col = my.cols2
  )


circos.trackPlotRegion(track.index = 1, 
                       panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim),
              ylim[1] + 0.1, 
              sector.name, 
              facing = "clockwise", 
              niceFacing = TRUE,
              adj = c(0, 0.5),
              cex = 0.8)
  #circos.axis(h = FALSE, 
              #major.at = NULL, 
              #labels.cex = 0.6,
              #minor.ticks = FALSE,
             # major.tick.length = NULL, 
              #sector.index = sector.name,
              #track.index = 2,
              #labels.pos.adjust = TRUE)
},
bg.border = NA)

fig1
```

###Making the same plot but with less countries
```{r, echo = FALSE, results = 'hide'}
net_matrix2 <- net_matrix2[-c(44 : 32), -c(44 : 32)]
net_matrix2 <- net_matrix2[-c(30, 29, 25, 23), -c(30, 29, 25, 23)]
net_matrix2 <- net_matrix2[-c(27), -c(27)]

#pdf(here("R", "Countriy collabs_1.pdf"), width = 10, height = 10)
fig2 <- chordDiagram(net_matrix2,
               annotationTrack = "grid",
               preAllocateTracks = 1, 
               grid.col = my.cols2
  )


circos.trackPlotRegion(track.index = 1, 
                       panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim),
              ylim[1] + 0.1, 
              sector.name, 
              facing = "clockwise", 
              niceFacing = TRUE,
              adj = c(0, 0.5),
              cex = 1.2)
  #circos.axis(h = FALSE, 
              #major.at = NULL, 
              #labels.cex = 0.6,
              #minor.ticks = FALSE,
             # major.tick.length = NULL, 
              #sector.index = sector.name,
              #track.index = 2,
              #labels.pos.adjust = TRUE)
},
bg.border = NA)
#title("Country collaborations", font.main = 1, cex.main = 1.8)

#dev.off()

fig2
```

### Making the plot getting rid of collabs with the same country

```{r}
net_matrix3 <- net_matrix2
diag(net_matrix3) <- 0 #get rid of collaboration with same country

#pdf(here("R", "Countriy collabs_2.pdf"), width = 10, height = 10)
fig3 <- chordDiagram(net_matrix3,
               annotationTrack = "grid",
               preAllocateTracks = 1, 
               grid.col = my.cols2
  )


circos.trackPlotRegion(track.index = 1, 
                       panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim),
              ylim[1] + 0.1, 
              sector.name, 
              facing = "clockwise", 
              niceFacing = TRUE,
              adj = c(0, 0.5),
              cex = 1.2)
  #circos.axis(h = FALSE, 
              #major.at = NULL, 
              #labels.cex = 0.6,
              #minor.ticks = FALSE,
             # major.tick.length = NULL, 
              #sector.index = sector.name,
              #track.index = 2,
              #labels.pos.adjust = TRUE)
},
bg.border = NA)
#title("Country collaborations", font.main = 1, cex.main = 1.8)

#dev.off()

fig3
```




### Panel 
Saving panel as a PDF
```{r, eval = FALSE}
#pdf(here("R", "Country_collabs.pdf"), width = 8, height = 10)

#layout(matrix(1:2, 1, 2))
par(mfrow = c(2, 1),
    mar = c(0.5, 0.5, 0.3, 0.5), 
    bg = rgb(1, 1, 1, 0.1),
    adj = 0, cex = 0.7)

fig2 <- chordDiagram(net_matrix2,
               annotationTrack = "grid",
               preAllocateTracks = 1, 
               grid.col = my.cols2
  )

circos.trackPlotRegion(track.index = 1, 
                       panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim),
              ylim[1] + 0.1, 
              sector.name, 
              facing = "clockwise", 
              niceFacing = TRUE,
              adj = c(0, 0.5),
              cex = 1.2)
  #circos.axis(h = FALSE, 
              #major.at = NULL, 
              #labels.cex = 0.6,
              #minor.ticks = FALSE,
             # major.tick.length = NULL, 
              #sector.index = sector.name,
              #track.index = 2,
              #labels.pos.adjust = TRUE)
},
bg.border = NA)
#title("A",font.main = 1, cex.main = 1.2)


fig3 <- chordDiagram(net_matrix3,
               annotationTrack = "grid",
               preAllocateTracks = 1, 
               grid.col = my.cols2
  )

circos.trackPlotRegion(track.index = 1, 
                       panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim),
              ylim[1] + 0.1, 
              sector.name, 
              facing = "clockwise", 
              niceFacing = TRUE,
              adj = c(0, 0.5),
              cex = 1.2)
  #circos.axis(h = FALSE, 
              #major.at = NULL, 
              #labels.cex = 0.6,
              #minor.ticks = FALSE,
             # major.tick.length = NULL, 
              #sector.index = sector.name,
              #track.index = 2,
              #labels.pos.adjust = TRUE)
},
bg.border = NA)
#title("B", font.main = 1, cex.main = 1.2)

#dev.off()
```


```{r setup, echo = FALSE, results = 'hide'}

```






OK

Now, I want to make the same graph but only for the 